trigger:
- main

pool:
  vmImage: 'ubuntu-20.04' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: '20210216.1'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: CmdLine@2
  inputs:
    script: 'sudo apt update && sudo apt upgrade -y'
    failOnStderr: true